version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-cicd-handson"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-54jwrv7zzvrf"
s3_prefix = "lambda-cicd-handson"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
